[package]
name = "eventsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4"
simconnect-sdk = { git = "https://github.com/mihai-dinculescu/simconnect-sdk-rs", branch = "main", features = ["derive"] }
